### ISSUE TITLE
Stopped working in zsh

### ISSUE THREAD

**Issue by rncain** [secretGeek/ok-bash#10]
Something in commit b3250a903e9c5949d20778ce4eb3ad47837b5322 has added something that causes an issue with zsh.

I'm running Zsh on MacOS

```
ok
ok:80: bad substitution
```

**Comment by secretGeek** [comment]
interesting. Do you have a .ok that it's trying to read?

**Comment by atlib77** [comment]
I got the same. But works if I run it from bash. Ran it on ok-bash root directory so the .ok file is in the repo.

**Comment by AshtonIzmev** [comment]
That commit https://github.com/secretGeek/ok-bash/commit/b3250a903e9c5949d20778ce4eb3ad47837b5322 indeed broke zsh compatibility.

Zsh does not accept indirect expansion (but bash does) to go from a variable name to its value.
https://unix.stackexchange.com/a/119442/310341
The following line here will not work :
`export "$x"="${!x}"`
And there may be an issue at least on my configuration with grep that returns binary files
`set | grep "^_OK_" | awk -F '=' '{print $1}')`

Solved on my laptop both on zsh with the following code L92:L96
`
    for x in $(set | grep --binary-files=text "^_OK_" | awk -F '=' '{print $1}'); do 
            export "$x"="${(P)x}" 
    done
`

Should we fork for a Zsh ? Or create a ok_zsh.sh ? Or simply patch the bash version ? (need to check bash compatibility then).
Anyway, ok is an awesome idea. Thanks

**Comment by doekman** [comment]
I will look into this somewhere in september (because [Training: moving to zsh](https://www.prowarehouse.nl/oplossingen-diensten/pro-academy-en/moving-to-zsh-en)). 

I think ok-bash should work on zsh as well. Thanks for you patience.

**Comment by doekman** [comment]
There were two cases of _bad substition_, and that was an easy fix. Changed `export "$x"="${!x}"` to `export "$x"` (the art of omission), see `zsh-fix`-branch.

However, there still are some issues.

**Comment by slidesecurity** [comment]
People always ask what is "ok."  I always refer them to this repo.  Unfortunately, it doesn't work out of the box for most mac users because of the need to switch to the zsh branch.  I think it should be merged into master if possible.

**Comment by doekman** [comment]
The `zsh-fix` branch doesn't contain something improvements anymore (I'll remove it later).

Yes, I agree zsh should work. I'll look into it when I have time (no promises).

**Comment by doekman** [comment]
See this PR: https://github.com/secretGeek/ok-bash/pull/36

**Comment by doekman** [comment]
Zsh support is done. Implementation of autocomplete is another issue.

Can this be tested, if you still use it? You will need to checkout the `zsh-support` branch.

@slidesecurity @AshtonIzmev @atlib77 @rncain

**Comment by doekman** [comment]
Merged.
