### ISSUE TITLE
Add —summary

### ISSUE THREAD

**Issue by secretGeek** [secretGeek/ok-bash#32]
An option `—summary` would list only the names commands, and all on one line

This idea stolen ruthlessly from ‘just’ 

https://github.com/casey/just#listing-available-recipes

$ just --summary
build test deploy lint

You could in theory make it the default via a configuration setting, when entering folders etc. if it works out to be a good idea I mean. (I’m such case it’s would probably only use summary if there were named commands in the file...)

(See also [same suggestions at ok-ps](https://github.com/secretGeek/ok-ps/issues/11))

**Comment by doekman** [comment]
I forgot a bit about this one. It kinda has it right now:

    ok --sys-cmds

From help: _Show all commands, space seperated (used for auto-complete)_.

But you probably mean without system commands (like list)?
